### ISSUE TITLE
Zinc 0.3.7 fails with NoSuchMethodError

### ISSUE THREAD

**Issue by pniederw** [typesafehub/zinc#87]
JDK 1.8, Scala 2.11.7, Zinc 0.3.7, Gradle 2.5. Scala 2.11 variant used for all Scala libraries.
The following error occurs during Zinc compilation. Compiling with Ant instead of Zinc solves the problem.

```
Caused by: java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
	at sbt.inc.Relations$.construct(Relations.scala:215)
	at sbt.inc.TextAnalysisFormat$RelationsF$.read(TextAnalysisFormat.scala:174)
	at sbt.inc.TextAnalysisFormat$$anonfun$2.apply(TextAnalysisFormat.scala:73)
	at sbt.inc.TextAnalysisFormat$$anonfun$2.apply(TextAnalysisFormat.scala:73)
	at sbt.inc.FormatTimer$.aggregate(TextAnalysisFormat.scala:18)
	at sbt.inc.FormatTimer$.time(TextAnalysisFormat.scala:25)
	at sbt.inc.TextAnalysisFormat$.read(TextAnalysisFormat.scala:73)
	at sbt.inc.FileBasedStore$$anon$1$$anonfun$getUncaught$1.apply(FileBasedStore.scala:18)
	at sbt.inc.FileBasedStore$$anon$1$$anonfun$getUncaught$1.apply(FileBasedStore.scala:18)
	at sbt.Using.apply(Using.scala:24)
	at sbt.inc.FileBasedStore$$anon$1.getUncaught(FileBasedStore.scala:18)
	at sbt.inc.FileBasedStore$$anon$1.get(FileBasedStore.scala:16)
	at sbt.inc.AnalysisStore$$anon$1.get(AnalysisStore.scala:22)
	at com.typesafe.zinc.Compiler$$anon$1$$anonfun$get$1$$anonfun$apply$2.apply(Compiler.scala:96)
	at com.typesafe.zinc.Compiler$$anon$1$$anonfun$get$1$$anonfun$apply$2.apply(Compiler.scala:96)
	at com.typesafe.zinc.Cache.get(Cache.scala:41)
	at com.typesafe.zinc.Compiler$$anon$1$$anonfun$get$1.apply(Compiler.scala:96)
	at com.typesafe.zinc.Compiler$$anon$1$$anonfun$get$1.apply(Compiler.scala:96)
	at scala.Option.flatMap(Option.scala:171)
	at com.typesafe.zinc.Compiler$$anon$1.get(Compiler.scala:96)
	at sbt.inc.AnalysisStore$$anon$1.get(AnalysisStore.scala:22)
	at sbt.inc.AnalysisStore$$anon$2.get(AnalysisStore.scala:28)
	at com.typesafe.zinc.Compiler$.analysis(Compiler.scala:107)
	at com.typesafe.zinc.Inputs$$anonfun$analysisFor$1.apply(Inputs.scala:160)
	at com.typesafe.zinc.Inputs$$anonfun$analysisFor$1.apply(Inputs.scala:160)
	at scala.Option.map(Option.scala:146)
	at com.typesafe.zinc.Inputs$.analysisFor(Inputs.scala:160)
	at com.typesafe.zinc.Inputs$$anonfun$4.apply(Inputs.scala:83)
	at com.typesafe.zinc.Inputs$$anonfun$4.apply(Inputs.scala:83)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.typesafe.zinc.Inputs$.inputs(Inputs.scala:83)
	at com.typesafe.zinc.Inputs$.create(Inputs.scala:107)
	at com.typesafe.zinc.Inputs.create(Inputs.scala)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:62)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:48)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
```

**Comment by SethTisue** [comment]
this looks a Scala 2.10 vs Scala 2.11 issue

**Comment by pniederw** [comment]
I know, but I can't spot anything Scala 2.10 related on my compile class path. Zinc Scala 2.10 issue?

**Comment by retronym** [comment]
SBT and Zinc themselves [require Scala 2.10](https://github.com/typesafehub/zinc/blob/master/project/ZincBuild.scala#L16). This will remain the case through the whole SBT 0.13.x series, and stems from the need to support plugins.

**Comment by pniederw** [comment]
Require in what way exactly? How am I supposed to build Scala 2.11 code with Zinc 0.3.7? Worked well until recently, now blows up with NoSuchMethodError.

**Comment by dwijnand** [comment]
sbt and zinc, as well as sbt's plugins, are built in Scala 2.10 and use Scala 2.10 standard library.

However they can still compile other versions of Scala.

I think the support versions are 2.9.x, 2.10.x, 2.11.x.

I think we need an example reproduction of the error to diagnose better.

**Comment by pniederw** [comment]
Thanks for the explanations. I meanwhile found the problem, and this issue can be closed. For the record: 

To enforce a particular Scala version, my Gradle build had this:

```
configurations {
  all {
    resolutionStrategy {
      force "org.scala-lang:scala-reflect:2.11.7"
    }
  }
}
```

Unfortunately, `configurations.all` includes the `zinc` configuration used to run Zinc. Here is the fix:

```
configurations {
  all {
    if (it.name != "zinc") {
      resolutionStrategy {
        force "org.scala-lang:scala-reflect:$scalaVersion"
      }
    }
  }
}
```

**Comment by thisismana** [comment]
@pniederw This issue seems not to be resolved. I just tried to upgrade a project from `gradle 2.11` to `gradle 2.12` and `gradle 2.13`, but the error you mentioned at the very top appeared.

This does not happen with `gradle 2.11`.

The scala version I was targeting is `2.11.8`. Would it be possible to upgrade your gradle build to the latest version and confirm that?

**Comment by thisismana** [comment]
Found a solution to force `zinc` to use a specific scala version

    dependencies {
        zinc 'com.typesafe.zinc:zinc:0.3.9'
        zinc 'org.scala-lang:scala-library:2.10.5'
    }
